services:
  web:
    container_name: web
    build:
      context: ./docker/nginx/
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - app
      - db

  app:
    container_name: app
    build:
      context: ./docker/app/
    ports:
      - "5173:5173"
    volumes:
      - ./src:/var/www/html/
      - ./docker/app/www.conf:/etc/php-fpm.d/www.conf
      - ./docker/app/php.ini:/etc/php.ini

  db:
    container_name: pgdb
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
      - pgdb-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: laravel_db
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel

  mail:
    image: mailhog/mailhog
    ports:
      - 8025:8025

volumes:
  pgdb-volume:
